### ISSUE TITLE
linking extention doesnt work on opera after you press task tackler on sparxmarths

### ISSUE THREAD

**Issue by BROtherrrrdffgrtgwr3** [davedude1011/taskTackler#1]

**Comment by TheProCut** [comment]
Same issue on chrome.

**Comment by davedude1011** [comment]
ive released a new version which should fix this, currently pending review for submission. should be fixed by the 30th

**Comment by BROtherrrrdffgrtgwr3** [comment]
Thanks mate Sent from my iPhoneOn 28 Sep 2024, at 11:52, davedude1011 ***@***.***> wrote:﻿
ive released a new version which should fix this, currently pending review for submission. should be fixed by the 30th
