### ISSUE TITLE
Auto bookwork and The solution button doesnt always show the answer

### ISSUE THREAD

**Issue by BROtherrrrdffgrtgwr3** [davedude1011/taskTackler#4]
Sorry to  bother you again for the 2nd time but autobook work doesnt work on opera as well as the solution button only somtimes gives the answer ill try restarting the extention but if oyu could look into it that would be great !

**Comment by davedude1011** [comment]
> Sorry to bother you again for the 2nd time but autobook work doesnt work on opera as well as the solution button only somtimes gives the answer ill try restarting the extention but if oyu could look into it that would be great !

For the solution button, sometimes it can't find a solution and will return a blank page, there's not really much I can do about that, other than adding a message saying "nothing found" or smthn. But could you explain more about the autobookwork not working

**Comment by BROtherrrrdffgrtgwr3** [comment]
That’s alr if you can’t do anything abt the solution not working it’s alr I’ll just use guath ai for that but for the auto book work not working basically I start my spars maths and I get my first book work check it’s says bookwork not found for where it’s ment to tell me which one I’m supposed to press nothing more just gives me a book work not found message and then I have to guess which one to press On 3 Oct 2024, at 07:59, davedude1011 ***@***.***> wrote:﻿

Sorry to bother you again for the 2nd time but autobook work doesnt work on opera as well as the solution button only somtimes gives the answer ill try restarting the extention but if oyu could look into it that would be great !

For the solution button, sometimes it can't find a solution and will return a blank page, there's not really much I can do about that. But could you explain more about the autobookwork not working

**Comment by davedude1011** [comment]
ok ill look into it, would you say you've done over 150 sparx maths questions since the start of this week? it might be a storage capacity problem

**Comment by BROtherrrrdffgrtgwr3** [comment]
Yea I might have done maybe like 150 but I’m not too sure but possibly Sent from my iPhoneOn 3 Oct 2024, at 16:21, davedude1011 ***@***.***> wrote:﻿
ok ill look into it, would you say you've done over 150 sparx maths questions since the start of this week? it might be a storage capacity problem

**Comment by BROtherrrrdffgrtgwr3** [comment]
also it looks like this 
![image_2024-10-03_163031609](https://github.com/user-attachments/assets/c9de43b2-192a-4729-8769-7461a7bb5ace)

**Comment by davedude1011** [comment]
ok the issue is probably from storage limitations, ill release a potential fix on the next update 👍

**Comment by BROtherrrrdffgrtgwr3** [comment]
thanks mate could i ask when the next update will be ?

**Comment by davedude1011** [comment]
ill try and fix the issue this week 👍 

> thanks mate could i ask when the next update will be ?

**Comment by SparxHomework** [comment]
Hello,
I love your AI but will the solution button ever work?

**Comment by SparxHomework** [comment]
It gives me answers that aren't correct

**Comment by SparxHomework** [comment]
or like nothing shows

**Comment by BROtherrrrdffgrtgwr3** [comment]
read form the top he cant do much about it wait try using gauth on  your phone or on your computer by using the snipping tool on windows search if you search it up  just snip the question and ctrl V into gauth ai

**Comment by davedude1011** [comment]
ok ive released v3.4 which should fix this issue, it should take a day or so for google to update it.
