### ISSUE TITLE
Sparx

### ISSUE THREAD

**Issue by Bj-3** [davedude1011/taskTackler#5]
Automatic solution doesn't work as intended. (I use the chrome extension on the official Chrome web store if that helps)
screenshot:
![Screenshot 2024-10-04 174636](https://github.com/user-attachments/assets/1b975e41-2b4f-494c-94b2-c7041b5933db)

**Comment by davedude1011** [comment]
yea sometimes it cant find an answer, ill be sure to add a popup for that on the next version

**Comment by SparxHomework** [comment]
Wanted to let u know the solution button gives wrong answers sometimes heads up

**Comment by Bj-3** [comment]
I know that, thanks so much!

**Comment by davedude1011** [comment]
ok ive released v3.4 which should fix this issue, it should take a day or so for google to update it.
