### ISSUE TITLE
Bro i understand you might  not  want to  hear  this  but  the book work  was working id say  maybe like 5 times in a row   untill it gave me the  bookwork not  found message

### ISSUE THREAD

**Issue by BROtherrrrdffgrtgwr3** [davedude1011/taskTackler#6]

**Comment by davedude1011** [comment]
After the first "bookwork not found" did they continue not to work for all the other checks?

**Comment by BROtherrrrdffgrtgwr3** [comment]
> After the first "bookwork not found" did they continue not to work for all the other checks?

yea  the next one  didnt   work  but  then after that one  it worked  then it   didnt

**Comment by BROtherrrrdffgrtgwr3** [comment]
also  i  found this error 
![image](https://github.com/user-attachments/assets/0ac57914-ca2e-4ab5-9ef5-f9e2a67e0876)

**Comment by SparxHomework** [comment]
bookwork sometimes doesnt work for me either

**Comment by davedude1011** [comment]
Problems relating bookwork checks should be fixed in the upcoming v4
