### ISSUE TITLE
Chatbot

### ISSUE THREAD

**Issue by Boywith222** [davedude1011/taskTackler#7]
So firstly the bookwork dosent work as well as it used to and the chatbot needs image reading for gods sake i pay 30 pounds for just chatgpt but worse HELL NO! also i am offering to help you with this i know some html python and scripting i could fix all of this ive seen the inspect element and i did fix it well until i refreshed the page but yes please contact me at ollypeterson640@gmail.com i will save this amazing tool for the greater good (ngl but im not tripping i need task tackler bro so let me INNNN 💀💀💀_

**Comment by Boywith222** [comment]
answer im not asking im saying i need a discord cal wid you i already sent a freind request

**Comment by davedude1011** [comment]
> answer im not asking im saying i need a discord cal wid you i already sent a freind request

sure, ill message you on discord
